## Nivell 1







Familiaritza't amb la Programació Numèrica a través de la llibreria NumPy.

**Exercici 
1:**
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import numpy as np

In [79]:
def estadistics(array):
    print('\n','* '*30,'\n','              Dades d\'estadística de l\'array',"\n",'* '*30,'\n')
    print(f"L'array està format per {len(array)} números.")
    print(f"Els valors de l'array es troben entre {array.min()} i {array.max()} (valors mínim i màxim respectivament).")
    print(f"La mitja aritmètica dels valors de l'array és {array.mean()}.")
    print(f"El quantil 0.25 de l'array és {np.quantile(array,0.25)}.")
    print(f"El valor mitjà (quantil 0.5) de l'array és {np.median(array)}.")
    print(f"El quantil 0.75 de l'array és {np.quantile(array,0.75)}.")
    print(f"La variança dels valors de l'array és {array.var()}.")
    print(f"La desviació estandard dels valors de l'array és {array.std()}.")

def estadistics1D(array):    
    if array.ndim!=1:
        print('\n','* '*30,'\n',"         L'array ha de ser d'una sola dimensió!\n",'* '*30,'\n')
    elif len(array)==1:
        print('\n','* '*40,'\n',"    L'array només conté un element i la informació estadística no té utilitat.\n",'* '*40,'\n')
    else:
        estadistics(array) 

In [80]:
array1=np.random.randint(10,size=1)
array2=np.random.randint(10,13,size=(3,4))
array3=np.random.randint(101,size=30)
print(array1,'\n')
estadistics1D(array1)
print(array2,'\n')
estadistics1D(array2)
print(array3,'\n')
estadistics1D(array3)

[6] 


 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  
     L'array només conté un element i la informació estadística no té utilitat.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  

[[11 12 10 12]
 [12 10 11 11]
 [10 10 11 10]] 


 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  
          L'array ha de ser d'una sola dimensió!
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  

[82 99 13 79 22 59 50 52 11 83 61 89 49 33 57 36 50 77  4 83 94 69  6 23
 69 78  8 54 91 85] 


 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  
               Dades d'estadística de l'array 
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *  

L'array està format per 30 números.
Els valors de l'array es troben entre 4 i 99 (valors mínim i màxim respectivament).
La mitja aritmètica dels valors de l'array és 55.53333333333333.
El quantil 0.25 de l'array és 33.75.
El valor mitjà (quantil 0.5) 

**Exercici 
2:**
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [74]:
def arrayNN(n):
    array=np.random.randint(101,size=(n,n))
    return array
print('\n')
n=int(input("Quants números per fila i columna vols (número sencer!)?\n>>> "))

nouArray=arrayNN(n)
print ('\n',' *'*3,f'Array generat de {n} x {n}',' *'*3,'\n',nouArray, '\n')



Quants números per fila i columna vols (número sencer!)?
>>> 4

  * * * Array generat de 4 x 4  * * * 
 [[56 20  2 98]
 [78 91 12 89]
 [88 94 32 28]
 [93 33 69 54]] 



**Exercici 
3:**
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.


In [138]:
def totalsArray2D (array):  
    for i in range (0,np.shape(array)[0]): 
        print(f"Els valors de la {i+1}a fila sumen {array[i,:].sum()}.")
    print('')
    for i in range (0,np.shape(array)[1]):
        print(f"Els valors de la {i+1}a columna sumen {array[:,i].sum()}.")
    

array=np.random.randint(101,size=(6,7))
print(array,'\n')
totalsArray2D(array)

[[ 38  67  22 100  21  59  24]
 [ 16   1  32   5  18  85   9]
 [ 67   4   7 100  36  42  83]
 [ 79  15  32  20  49  93   7]
 [  4  70  86  87  93  96   5]
 [ 65  80  88  82  71   1  88]] 

Els valors de la 1a fila sumen 331.
Els valors de la 2a fila sumen 166.
Els valors de la 3a fila sumen 339.
Els valors de la 4a fila sumen 295.
Els valors de la 5a fila sumen 441.
Els valors de la 6a fila sumen 475.

Els valors de la 1a columna sumen 269.
Els valors de la 2a columna sumen 237.
Els valors de la 3a columna sumen 267.
Els valors de la 4a columna sumen 394.
Els valors de la 5a columna sumen 288.
Els valors de la 6a columna sumen 376.
Els valors de la 7a columna sumen 216.


**Exercici 
4:**
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [75]:
def coefCorrelation(array1D_a, array1D_b): #Dos arrays unicimensionals qua haurien de ser del mateix tamany
    mean_multipXY=0
    covarXY=0
    if array1D_a.ndim!= array1D_b.ndim:#control per si són de diferent tamany!! Potser no caldria...
        print ("Les dimensions dels dos arrays són diferents, no es pot realitzar la correlació!")
        return 0
    else:
        for i in range (0, np.size(array1D_a)):
            mean_multipXY+= (array1D_a[i]* array1D_b[i])/np.size(array1D_a) #per generar la mitja del producte XY
        covarXY=mean_multipXY-(np.mean(array1D_a)*np.mean(array1D_b))
        return covarXY/(np.std(array1D_a)*np.std(array1D_b)) 

def matrix_coef_corr(arraynD):
    array_coef_corr=np.ones(shape=(np.shape(arraynD)[1],np.shape(arraynD)[1])) # la base de la matriu de correlació, tenim diagonal amb 1
    for i in range(0,np.shape(arraynD)[1]):
        for j in range (i+1,np.shape(arraynD)[1]):#matriu és simètrica, omplim la meitat e igualem invertint indexs
            array_coef_corr[i,j]=coefCorrelation(arraynD[:,i],arraynD[:,j])
            array_coef_corr[j,i]= array_coef_corr[i,j]
    return array_coef_corr 

In [76]:
array=np.random.randint(101,size=(6,3))
print(array)
print('\n','* '*3, 'Matriu amb els Coeficients de Correlació de Pearson', '* '*3,'\n')
print(matrix_coef_corr(array))


[[86 31 42]
 [81 43 30]
 [26 97 43]
 [27 12 87]
 [50 93  8]
 [81 71 80]]

 * * *  Matriu amb els Coeficients de Correlació de Pearson * * *  

[[ 1.         -0.18726441 -0.13723297]
 [-0.18726441  1.         -0.4879828 ]
 [-0.13723297 -0.4879828   1.        ]]


**Usos i interpretació del coeficient de correlació de Pearson.**
El coeficient de correlació de Pearson dóna informació sobre dependencia lineal entre dos variables. 
Té un valor comprès entre -1 i +1. En els extrems hi ha la màxima dependència (1 o -1), 
si és 1 la dependència serà la màxima i directe (si un creix l'atre també), si és -1 la correlació és 
la màxima però inversa (si un creix l'altre disminueix).
Si el valor és 0, no hi ha gens de correlació lineal entre les dues variables.